//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiDangSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiDangSanPham()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.DiemTichLuys = new HashSet<DiemTichLuy>();
            this.ThongBaos = new HashSet<ThongBao>();
            this.TraoDois = new HashSet<TraoDoi>();
        }
    
        public int maBDSP { get; set; }
        public int maND { get; set; }
        public int maLSP { get; set; }
        public string tenSP { get; set; }
        public string noiDung { get; set; }
        public string hinhAnh { get; set; }
        public string video { get; set; }
        public int maTT { get; set; }
        public decimal gia { get; set; }
        public int soLuong { get; set; }
        public System.DateTime ngayDang { get; set; }
        public Nullable<System.DateTime> ngayThayDoi { get; set; }
        public string ghiChu { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TrangThaiBaiDang TrangThaiBaiDang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemTichLuy> DiemTichLuys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraoDoi> TraoDois { get; set; }
    }
}
