//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCao
    {
        public int maBC { get; set; }
        public Nullable<int> maND { get; set; }
        public Nullable<int> maNDKhac { get; set; }
        public string lyDo { get; set; }
        public Nullable<System.DateTime> ngayBaoCao { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
