//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BinhLuan()
        {
            this.ThongBaos = new HashSet<ThongBao>();
        }
    
        public int maBL { get; set; }
        public int maND { get; set; }
        public Nullable<int> maBDSP { get; set; }
        public Nullable<int> maBDTT { get; set; }
        public string noiDung { get; set; }
        public string trangThai { get; set; }
        public System.DateTime ngayBL { get; set; }
    
        public virtual BaiDangSanPham BaiDangSanPham { get; set; }
        public virtual BaiDangThongTin BaiDangThongTin { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
    }
}
