//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoi_BaiQuiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CauHoi_BaiQuiz()
        {
            this.KetQuas = new HashSet<KetQua>();
        }
    
        public int MaCHBQ { get; set; }
        public int MaCH { get; set; }
        public int MaBQ { get; set; }
        public double Diem { get; set; }
    
        public virtual BaiQuiz BaiQuiz { get; set; }
        public virtual CauHoi CauHoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQua> KetQuas { get; set; }
    }
}
