//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucNangTaiKhoan
    {
        public string Email { get; set; }
        public int maLoaiTK { get; set; }
        public int ID { get; set; }
    
        public virtual LoaiTaiKhoan LoaiTaiKhoan { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
