//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DapAn
    {
        public int maDapAn { get; set; }
        public int maCauHoi { get; set; }
        public string NoiDungDapAn { get; set; }
        public bool dapAn1 { get; set; }
    
        public virtual CauHoi CauHoi { get; set; }
    }
}
