//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemTichLuy
    {
        public int maDTL { get; set; }
        public int maND { get; set; }
        public double diem { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
        public Nullable<int> maBDTT { get; set; }
        public Nullable<int> maBDSP { get; set; }
        public Nullable<int> maQG { get; set; }
    
        public virtual BaiDangSanPham BaiDangSanPham { get; set; }
        public virtual BaiDangThongTin BaiDangThongTin { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual QuyenGop QuyenGop { get; set; }
    }
}
