//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonQua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonQua()
        {
            this.DiemTichLuys = new HashSet<DiemTichLuy>();
            this.ThongBaos = new HashSet<ThongBao>();
        }
    
        public int MaDQ { get; set; }
        public int MaND { get; set; }
        public int MaQT { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string TrangThai { get; set; }
        public double TongDiem { get; set; }
        public string DiaChi { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemTichLuy> DiemTichLuys { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual QuaTang QuaTang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
    }
}
