//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonThuGom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonThuGom()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
        }
    
        public int maDonTG { get; set; }
        public int maDVTG { get; set; }
        public string trangThai { get; set; }
        public Nullable<System.DateTime> ngayGui { get; set; }
        public Nullable<System.DateTime> ngayXacNhan { get; set; }
        public Nullable<System.DateTime> ngayHoanTat { get; set; }
        public string viTriTG { get; set; }
        public string thanhPhan { get; set; }
        public string ghiChu { get; set; }
        public string khoiLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual DonViThuGom DonViThuGom { get; set; }
    }
}
