//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KetQua()
        {
            this.DiemTichLuys = new HashSet<DiemTichLuy>();
        }
    
        public int maKQ { get; set; }
        public int maND { get; set; }
        public int maCDBQ { get; set; }
        public Nullable<double> TongDiem { get; set; }
    
        public virtual ChuDeBaiQuiz ChuDeBaiQuiz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemTichLuy> DiemTichLuys { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
