//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQua
    {
        public int maKQ { get; set; }
        public int maND { get; set; }
        public int maCHBQ { get; set; }
        public Nullable<int> MaDA { get; set; }
        public Nullable<int> LuotLamBai { get; set; }
        public Nullable<double> TongDiem { get; set; }
    
        public virtual CauHoi_BaiQuiz CauHoi_BaiQuiz { get; set; }
        public virtual DapAn DapAn { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
