//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELFVanLang2021Entities : DbContext
    {
        public ELFVanLang2021Entities()
            : base("name=ELFVanLang2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BaiDangSanPham> BaiDangSanPhams { get; set; }
        public virtual DbSet<BaiDangThongTin> BaiDangThongTins { get; set; }
        public virtual DbSet<BaiQuiz> BaiQuizs { get; set; }
        public virtual DbSet<BinhLuan> BinhLuans { get; set; }
        public virtual DbSet<CauHoi> CauHois { get; set; }
        public virtual DbSet<CauHoi_BaiQuiz> CauHoi_BaiQuiz { get; set; }
        public virtual DbSet<ChucNangTaiKhoan> ChucNangTaiKhoans { get; set; }
        public virtual DbSet<ChuDeBaiQuiz> ChuDeBaiQuizs { get; set; }
        public virtual DbSet<DapAn> DapAns { get; set; }
        public virtual DbSet<DiemTichLuy> DiemTichLuys { get; set; }
        public virtual DbSet<DonQua> DonQuas { get; set; }
        public virtual DbSet<DonThuGom> DonThuGoms { get; set; }
        public virtual DbSet<DonViThuGom> DonViThuGoms { get; set; }
        public virtual DbSet<KetQua> KetQuas { get; set; }
        public virtual DbSet<LoaiDiemTichLuy> LoaiDiemTichLuys { get; set; }
        public virtual DbSet<LoaiQuyenGop> LoaiQuyenGops { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<LoaiTaiKhoan> LoaiTaiKhoans { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<PhuongThiTran> PhuongThiTrans { get; set; }
        public virtual DbSet<QuanHuyen> QuanHuyens { get; set; }
        public virtual DbSet<QuaTang> QuaTangs { get; set; }
        public virtual DbSet<QuyenGop> QuyenGops { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<Tinh_ThanhPho> Tinh_ThanhPho { get; set; }
        public virtual DbSet<ThongBao> ThongBaos { get; set; }
        public virtual DbSet<TrangThaiBaiDang> TrangThaiBaiDangs { get; set; }
        public virtual DbSet<TraoDoi> TraoDois { get; set; }
        public virtual DbSet<BaoCao> BaoCaos { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
    }
}
