//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.BaiDangSanPhams = new HashSet<BaiDangSanPham>();
            this.BaiDangThongTins = new HashSet<BaiDangThongTin>();
            this.BinhLuans = new HashSet<BinhLuan>();
            this.DiemTichLuys = new HashSet<DiemTichLuy>();
            this.DonQuas = new HashSet<DonQua>();
            this.KetQuas = new HashSet<KetQua>();
            this.QuyenGops = new HashSet<QuyenGop>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
            this.TinNhans = new HashSet<TinNhan>();
            this.ThongBaos = new HashSet<ThongBao>();
            this.ThongBaos1 = new HashSet<ThongBao>();
            this.TraoDois = new HashSet<TraoDoi>();
            this.TraoDois1 = new HashSet<TraoDoi>();
        }
    
        public int maND { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập họ và tên")]
        [StringLength(100, ErrorMessage = "Họ và tên không được quá 100 kí tự!")]
        [RegularExpression(@"[\p{L} ]+$", ErrorMessage = "Họ và tên chỉ được nhập chữ!")]
        public string hoVaTen { get; set; }
        [Required]
        public int gioiTinh { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập số điện thoại")]
        [RegularExpression(@"^(\d{10})$", ErrorMessage = "Số điện thoại không đúng định dạng!")]
        public string dienThoai { get; set; }
        public Nullable<int> maTinh_TP { get; set; }
        public Nullable<int> maQuan { get; set; }
        public Nullable<int> maP { get; set; }
        public string diaChi { get; set; }
        public string avatar { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string ghiChu { get; set; }
        public string maTK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiDangSanPham> BaiDangSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiDangThongTin> BaiDangThongTins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemTichLuy> DiemTichLuys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonQua> DonQuas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQua> KetQuas { get; set; }
        public virtual PhuongThiTran PhuongThiTran { get; set; }
        public virtual QuanHuyen QuanHuyen { get; set; }
        public virtual Tinh_ThanhPho Tinh_ThanhPho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuyenGop> QuyenGops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinNhan> TinNhans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraoDoi> TraoDois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraoDoi> TraoDois1 { get; set; }
    }
}
