//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int maTB { get; set; }
        public Nullable<int> maBDSP { get; set; }
        public Nullable<int> maBDTT { get; set; }
        public Nullable<int> maBL { get; set; }
        public Nullable<int> maTraoDoi { get; set; }
        public Nullable<int> maQG { get; set; }
        public Nullable<int> maDQ { get; set; }
        public string noiDung { get; set; }
        public System.DateTime ngayTB { get; set; }
        public string tinhTrang { get; set; }
        public int maND { get; set; }
        public Nullable<int> maNDKhac { get; set; }
    
        public virtual BaiDangSanPham BaiDangSanPham { get; set; }
        public virtual BaiDangThongTin BaiDangThongTin { get; set; }
        public virtual BinhLuan BinhLuan { get; set; }
        public virtual DonQua DonQua { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        public virtual QuyenGop QuyenGop { get; set; }
        public virtual TraoDoi TraoDoi { get; set; }
    }
}
